#!/usr/bin/osascript

(*
Waits for an authorization dialog to appear when instruments is launched, 
then dismisses it by entering the specified login password.

This is a workaround for http://openradar.appspot.com/radar?id=1544403.

This script is expected to be put into the background right before 
instruments is launched:

	osascript authorize_instruments "$LOGIN_PASSWORD" &
	# Kill the process when the parent script ends
	trap "kill $!" SIGINT SIGTERM EXIT

	xcrun instruments ...

*)

on run argv
	set loginPassword to item 1 of argv
	
	-- begin with a short delay, to catch the prompt under the assumption 
	-- that instruments will be launched immediately after this is run
	delay 4.0
	tell application "System Events"
		repeat while "SecurityAgent" is not in name of processes
			-- long delay: it is likely that the prompt will not appear this run
			-- and we don't want to impede instruments' performance
			delay 10.0
		end repeat
		tell process "SecurityAgent"
			set value of text field 2 of scroll area 1 of group 1 of window 1 to loginPassword
			click button "Take Control" of group 2 of window 1
			return	-- just so the script doesn't print the last command executed
		end tell
	end tell
end run
