#!/usr/bin/osascript

(*
For details and documentation:
http://github.com/inkling/Subliminal

Copyright 2013 Inkling Systems, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*)

(*
Checks to ensure that assistive device access is enabled 
so that GUI scripts may run, and returns true if it is, 
no if not.

If the setting is not enabled, the script will direct the user 
to open the Preferences and enable it.
*)

tell application "System Events"
	if not UI elements enabled then
		beep
		display dialog "GUI Scripting is not enabled" & return & return & "Open System Preferences and check Enable Access for Assistive Devices in the Accessibility (or Universal Access) preference pane, then run this script again." with icon 0 -- "stop" icon
		if button returned of result is "OK" then
			tell application "System Preferences"
				activate
				set current pane to pane "com.apple.preference.universalaccess"
			end tell
		end if
		return false
	end if
	return true
end tell
