#!/bin/sh

#  For details and documentation:
#  http://github.com/inkling/Subliminal
#
#  Copyright 2013 Inkling Systems, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#


# `reset_simulator` deletes all applications from the iPhone Simulator and resets 
# its settings.
#
# More precisely, `reset_simulator` resets the content and settings of the 
# SDK currently used by the Simulator. For example, if the Simulator is running 
# iOS 5.1 when this script is executed, all applications which had previously 
# been run on iOS 5.1 will be uninstalled; but the Simulator's content and settings 
# for iOS 6.1 will be unaffected.
#
# This script does not actually invoke the "Reset Content and Settings…" option 
# of the iOS Simulator's menu due to the unreliability of GUI scripting, 
# but reproduces that option's effects directly.

# Make sure to open the simulator corresponding to the current dev tools
SIMULATOR_PATH=`find "$(xcode-select -print-path)" -name "iPhone Simulator.app"`

# Open that simulator, to make sure that it is the last simulator
# to have written its preferences to `com.apple.iphonesimulator`
open "$SIMULATOR_PATH"
sleep 2.0

# Kill the simulator
killall "iPhone Simulator" 2> /dev/null
sleep 1.0

# Determine the SDK version e.g. "5.1" used by the simulator, from its preferences
SDK_ROOT=`defaults read com.apple.iphonesimulator currentSDKRoot`
SDK=`echo "$SDK_ROOT" | perl -pe 's|.*iphonesimulator(.+)\.sdk|$1|i'`

# Delete the `Application Support` directory for this SDK version
# This will erase both the content and settings for this version
rm -rf "$HOME/Library/Application Support/iPhone Simulator/$SDK"

# Restart the simulator, 
# causing it to recreate the support directory for the current SDK
open "$SIMULATOR_PATH"
sleep 2.0
