#!/bin/sh

#  For details and documentation:
#  http://github.com/inkling/Subliminal
#
#  Copyright 2013 Inkling Systems, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#


# `set_simulator_device` sets the simulator's device to the specified type.
# Execute `set_simulator_device` with no arguments to print usage.

print_usage_and_fail () {
	echo "usage: set_simulator_device <device>"
	echo "  <device>\tA device type like \"iPhone\"."
	echo "          \tAcceptable types are listed in the iPhone Simulator's \"Hardware -> Device\" menu."
	exit 1
}

DEVICE=$1
if [[ -z "$DEVICE" ]]; then
	print_usage_and_fail
fi

# Change device type
defaults write com.apple.iphonesimulator SimulateDevice "$DEVICE"

# Restart simulator
killall "iPhone Simulator" 2> /dev/null
sleep 1.0
open -a "iPhone Simulator"
sleep 1.0
