#!/bin/bash

# For details and documentation:
# http://github.com/inkling/Subliminal
#
# Copyright 2013 Inkling Systems, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#	http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Sets the simulator's device to the specified type.
#
# Acceptable types are listed in the iPhone Simulator's "Hardware -> Device" menu.

killall "iPhone Simulator" &> /dev/null

defaults write com.apple.iPhoneSimulator SimulateDevice $1

XCODE_PATH=`xcode-select --print-path`
open "$XCODE_PATH/Platforms/iPhoneSimulator.platform/Developer/Applications/iPhone Simulator.app"
