#!/bin/sh

#  For details and documentation:
#  http://github.com/inkling/Subliminal
#
#  Copyright 2013 Inkling Systems, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#


# `set_simulator_version` sets the SDK used by the iOS Simulator to the specified version.
# Execute `set_simulator_device` with no arguments to print usage.

print_usage_and_fail () {
	echo "usage: set_simulator_version <sdk_version>"
	echo "  <sdk_version>\tA string like \"5.1\" specifying the simulator SDK version to use."
	exit 1
}

SDK=$1
if [[ -z "$SDK" ]]; then
	print_usage_and_fail
fi

# Set new SDK root
# The quoting of "xcode-select" is just so that "select" doesn't mess up this file's syntax highlighting
SDK_ROOT=`find "$('xcode-select' -print-path)" -type d -iname "iphonesimulator$SDK.sdk"`
if [[ -z "$SDK_ROOT" ]]; then
	echo "Error: Simulator SDK $SDK not found."
	exit 1
fi
defaults write com.apple.iphonesimulator currentSDKRoot "$SDK_ROOT"

# Restart simulator
killall "iPhone Simulator" 2> /dev/null
sleep 1.0
# Make sure to open the Simulator corresponding to the current dev tools
SIMULATOR_PATH=`find "$(xcode-select -print-path)" -name "iPhone Simulator.app"`
open "$SIMULATOR_PATH"
sleep 2.0
