name: PR checks

on: [push]

jobs:
  checks:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3
      - name: Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: ^18.18.0
      - name: Install yarn
        run: npm install -g yarn
      - name: Pre-install
        run: rm -rf node_modules && yarn config set "strict-ssl" false -g
      - name: Setup .npmrc
        run: |
          npm config set "@inkling:registry" "https://inkling.jfrog.io/artifactory/api/npm/inkling/"
          npm config set "//inkling.jfrog.io/artifactory/api/npm/inkling/:_authToken" $NPM_JFROG_AUTH_TOKEN
        env:
          NPM_JFROG_AUTH_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

      - name: Install dependencies
        run: yarn --no-cache --no-progress --non-interactive --frozen-lockfile

      - name: Lint
        run: yarn --non-interactive lint

      - name: Build
        run: yarn --non-interactive build

      - name: Test
        run: yarn --non-interactive test
